name: Build and Push Devcontainer Images
on:
  workflow_dispatch:
  schedule:
    - cron: '40 16 1 * *'  # 16:40 UTC everyday
  merge_group:
  # pull_request:
  #   branches:
  #     - main
  #     - devel
  #     - testing
  #   paths-ignore:
  #     - '**.md'
  push:
    branches:
      - main
      - devel
      # - testing
    paths-ignore:
      - '**.md'
env:
    IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
    IMAGE_NAME: devcontainer

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build-devcontainers:
    name: build
    runs-on: ubuntu-latest
    continue-on-error: false
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false

    steps:
      - name: set TIMESTAMP
        run: echo "TIMESTAMP=$(date +'%Y%m%d.%H.%M.%S')" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Rust Devcontainer Image
        uses: devcontainers/ci@v0.3
        id: build_rust_container
        with:
          imageName: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}-rust
          imageTag: latest,${{ env.TIMESTAMP }}
          subFolder: "rust"
          cacheFrom: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}-rust
          push: always

      - name: Build CSharp Devcontainer Image
        uses: devcontainers/ci@v0.3
        id: build_csharp_container
        with:
          imageName: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}-csharp
          imageTag: latest,${{ env.TIMESTAMP }}
          subFolder: "csharp"
          cacheFrom: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}-csharp
          push: always

  build-devcontainers-with-cmdline-tools:
    name: build
    runs-on: ubuntu-latest
    needs: [ build-devcontainers ]
    continue-on-error: false
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false

    steps:
      - name: set TIMESTAMP
        run: echo "TIMESTAMP=$(date +'%Y%m%d.%H.%M.%S')" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build CSharp with Helix Devcontainer Image
        uses: devcontainers/ci@v0.3
        id: build_csharp_cmdline_tools_container
        with:
          imageName: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}-csharp-cmdline-tools
          imageTag: latest,${{ env.TIMESTAMP }}
          subFolder: "csharp-cmdline-tools"
          cacheFrom: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}-csharp-cmdline-tools
          push: always

  build-devcontainers-with-cmdline-tools-sshd:
    name: build
    runs-on: ubuntu-latest
    needs: [ build-devcontainers-with-cmdline-tools ]
    continue-on-error: false
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false

    steps:
      - name: set TIMESTAMP
        run: echo "TIMESTAMP=$(date +'%Y%m%d.%H.%M.%S')" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build CSharp with Helix Devcontainer Image
        uses: devcontainers/ci@v0.3
        id: build_csharp_cmdline_tools_sshd_container
        with:
          imageName: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}-csharp-cmdline-tools-sshd
          imageTag: latest,${{ env.TIMESTAMP }}
          subFolder: "csharp-cmdline-tools-sshd"
          cacheFrom: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}-csharp-cmdline-tools-sshd
          push: always

  check:
    name: Check all builds successful
    if: ${{ !cancelled() }}
    runs-on: ubuntu-latest
    needs: [build-devcontainers, build-devcontainers-with-cmdline-tools, build-devcontainers-with-cmdline-tools-sshd]
    steps:
      - name: Exit on failure
        if: ${{ needs.build_rust_container.result == 'failure' || needs.build_csharp_container.result == 'failure' ||  needs.build_csharp_cmdline_tools_container.result == 'failure' ||  needs.build_csharp_cmdline_tools_sshd_container.result == 'failure'}}
        shell: bash
        run: exit 1
      - name: Exit
        shell: bash
        run: exit 0
